/*
 * SimpleTwitter
 *
 * Simple REST API for service like a Twitter
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Like struct {
	TweetID int64 `json:"tweetId,omitempty"`

	Value int64 `json:"value,omitempty"`
}
