/*
 * SimpleTwitter
 *
 * Simple REST API for service like a Twitter
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Tweet struct {
	ID int64 `json:"id,omitempty"`

	AuthorID int64 `json:"authorId,omitempty"`

	Text string `json:"text,omitempty"`

	CreatedDateTimestamp int64 `json:"createdDateTimestamp,omitempty"`
}
