/*
 * SimpleTwitter
 *
 * Simple REST API for service like a Twitter
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/",
		Index,
	},

	Route{
		"DeleteLikeByTweetID",
		strings.ToUpper("Delete"),
		"/tweets/{tweetID}/likes",
		DeleteLikeByTweetID,
	},

	Route{
		"GetLikeByTweetID",
		strings.ToUpper("Get"),
		"/tweets/{tweetID}/likes",
		GetLikeByTweetID,
	},

	Route{
		"SetLikeByTweetID",
		strings.ToUpper("Post"),
		"/tweets/{tweetID}/likes",
		SetLikeByTweetID,
	},

	Route{
		"AddTweet",
		strings.ToUpper("Post"),
		"/tweets",
		AddTweet,
	},

	Route{
		"DeleteTweet",
		strings.ToUpper("Delete"),
		"/tweets/{tweetID}",
		DeleteTweet,
	},

	Route{
		"GetTweet",
		strings.ToUpper("Get"),
		"/tweets/{tweetID}",
		GetTweet,
	},

	Route{
		"GetTweetByAuthorID",
		strings.ToUpper("Get"),
		"/users/{authorId}/tweets",
		GetTweetByAuthorID,
	},

	Route{
		"UpdateTweet",
		strings.ToUpper("Put"),
		"/tweets/{tweetID}",
		UpdateTweet,
	},

	Route{
		"AddUser",
		strings.ToUpper("Post"),
		"/users",
		AddUser,
	},

	Route{
		"DeleteUser",
		strings.ToUpper("Delete"),
		"/users",
		DeleteUser,
	},

	Route{
		"GetUser",
		strings.ToUpper("Get"),
		"/users",
		GetUser,
	},
}
