/*
 * SimpleTwitter
 *
 * Simple REST API for service like a Twitter
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"

	sw "github.com/ptsypyshev/gb-golang-backend-level01/lesson03/simpleTwitterAPI/go"
)

func main() {
	log.Printf("Server started")

	router := sw.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))
}
